service:
  db:
    container_name: postgres_db
    image: postgres:alpine3.23
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTRGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - .env
    restart: unless-stopped
    volimes:
      - postres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      intervals: 5s
      timeout: 5s
      retries: 5
    
  web:
    build: .
    container_name: travel_app
    depends_on:
      db:
        condition: service_healty
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    ports: 
      - "8000:8000"
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: unless-stopped
    volumes:
      - .:/app
      
  migrate:
    build: .
    container_name: db_migrate
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "manage.py", "migrate"]
    env_file:
      - .env
